# Generated by Django 4.0 on 2021-12-28 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=True, verbose_name='默认地址')),
                ('lable', models.CharField(blank=True, default='', max_length=20, verbose_name='标签')),
                ('name', models.CharField(max_length=20, verbose_name='收货人')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('detail', models.CharField(max_length=200, verbose_name='详细地址')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
            },
        ),
        migrations.CreateModel(
            name='CustomerRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'VIP等级',
                'verbose_name_plural': 'VIP等级',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.IntegerField(verbose_name='手机')),
                ('wechat', models.CharField(max_length=50, verbose_name='微信号')),
                ('alipay', models.CharField(max_length=50, verbose_name='支付宝')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.IntegerField(verbose_name='手机')),
                ('wechat', models.CharField(max_length=50, verbose_name='微信号')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address', verbose_name='地址')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.IntegerField(verbose_name='手机')),
                ('wechat', models.CharField(max_length=50, verbose_name='微信号')),
                ('balance', models.FloatField(default=0, verbose_name='余额')),
                ('due', models.FloatField(default=0, verbose_name='欠款')),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.employee', verbose_name='专属客服')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address', verbose_name='地址')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customerrank')),
            ],
            options={
                'verbose_name': '顾客',
                'verbose_name_plural': '顾客',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.area', verbose_name='所属')),
            ],
            options={
                'verbose_name': '省市区',
                'verbose_name_plural': '省市区',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='more_detail', to='user.area', verbose_name='上级省市区'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user.person', verbose_name='联系人'),
        ),
    ]
