# Generated by Django 4.0 on 2021-12-28 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jewelry', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='订单号')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单日期')),
                ('total_count', models.IntegerField(verbose_name='总件数')),
                ('deduct', models.FloatField(verbose_name='优惠金额')),
                ('total_value', models.FloatField(verbose_name='总价')),
                ('comments', models.TextField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('is_payed', models.BooleanField(default=False, verbose_name='付款')),
                ('is_shiped', models.BooleanField(default=False, verbose_name='发货')),
                ('is_recieved', models.BooleanField(default=False, verbose_name='签收')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='user.customer', verbose_name='顾客')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Outlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateTimeField(blank=True, null=True, verbose_name='发货日期')),
                ('sign_date', models.DateTimeField(blank=True, null=True, verbose_name='签收日期')),
                ('carrier', models.CharField(blank=True, default='自提', max_length=20, verbose_name='承运')),
                ('track_no', models.CharField(blank=True, default='', max_length=20, verbose_name='运单号')),
                ('gross_weight', models.FloatField(default=0, verbose_name='毛重')),
                ('ship_fee', models.FloatField(verbose_name='运费')),
                ('packaging', models.FloatField(verbose_name='包装费')),
                ('insurance', models.FloatField(verbose_name='保险')),
                ('other_fee', models.FloatField(verbose_name='其它')),
            ],
            options={
                'verbose_name': '包裹',
                'verbose_name_plural': '包裹',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='退货日期')),
                ('actrual_price', models.FloatField(default=0, verbose_name='退款金额')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_record', to='user.customer', verbose_name='顾客')),
            ],
            options={
                'verbose_name': '退款',
                'verbose_name_plural': '退款',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SalesShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.FloatField(verbose_name='销售分成')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_share', to='user.employee', verbose_name='销售')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_share', to='b2c.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '销售分成',
                'verbose_name_plural': '销售分成',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='商品')),
                ('price', models.FloatField(default=0, verbose_name='标价')),
                ('deduct', models.FloatField(default=0, verbose_name='优惠')),
                ('actrual_price', models.FloatField(default=0, verbose_name='售价')),
                ('merchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_record', to='jewelry.merchandise', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_record', to='b2c.order', verbose_name='订单')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_record', to='b2c.package', verbose_name='包裹')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录',
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_record', to='b2c.package', verbose_name='包裹')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_record', to='b2c.refund', verbose_name='退货申请')),
                ('sales_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_record', to='b2c.salesrecord', verbose_name='销售记录')),
            ],
            options={
                'verbose_name': '退货记录',
                'verbose_name_plural': '退货记录',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_income', models.BooleanField(default=True, verbose_name='收入')),
                ('pay_type', models.CharField(choices=[('CASH', '现金'), ('BANK', '银行转账'), ('CRED', '信用卡付款'), ('WXZF', '微信支付'), ('WXZZ', '微信转账'), ('WXHB', '微信红包'), ('APZF', '支付宝支付'), ('APZZ', '支付宝转账'), ('BLCE', '店内余额')], max_length=4, verbose_name='付款方式')),
                ('amount', models.FloatField(verbose_name='付款金额')),
                ('pay_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='付款时间')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='截图')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay', to='b2c.order', verbose_name='订单')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay', to='b2c.refund', verbose_name='退货')),
            ],
            options={
                'verbose_name': '付款',
                'verbose_name_plural': '付款',
            },
        ),
    ]
