# Generated by Django 4.0 on 2021-12-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2c', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='description',
            field=models.CharField(max_length=100, verbose_name='商品描述'),
        ),
    ]
