# Generated by Django 4.0 on 2021-12-28 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=20, verbose_name='名称')),
                ('depot_type', models.CharField(choices=[('SL', '供应商'), ('WH', '仓库'), ('ST', '直营店'), ('AG', '代理商'), ('MT', '维修厂')], default='WH', max_length=2)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.address', verbose_name='地址')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.person', verbose_name='联系人')),
            ],
            options={
                'verbose_name': '场所',
                'verbose_name_plural': '场所',
            },
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='图像')),
                ('description', models.CharField(max_length=50, verbose_name='描述')),
                ('net_weight', models.FloatField(verbose_name='净重')),
                ('sku', models.CharField(help_text='配对的两颗宝石拥有相同sku;整包裸石拥有相同的sku;套装成品拥有相同的sku;同款多件拥有相同的sku。', max_length=20, verbose_name='款号')),
                ('sku_count', models.IntegerField(default=1, verbose_name='同款')),
                ('sku_description', models.CharField(max_length=20, verbose_name='款式')),
                ('supply_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入库时间')),
                ('manufacture', models.CharField(max_length=10, verbose_name='产地')),
                ('cost', models.FloatField(verbose_name='成本')),
                ('price', models.FloatField(verbose_name='标价')),
                ('margin', models.FloatField(verbose_name='价格浮动')),
                ('deleted', models.BooleanField(default=False)),
                ('depot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instock', to='jewelry.depot')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='jewelry.depot', verbose_name='供货商')),
            ],
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('merchandise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jewelry.merchandise')),
                ('metal_type', models.CharField(choices=[('PT', '铂金'), ('24KG', '24K金'), ('18KY', '18K黄'), ('18KW', '18K白'), ('18KR', '18K红'), ('14KY', '14K黄'), ('14KW', '14K白'), ('14KR', '14K红'), ('10KY', '14K黄'), ('10KW', '14K白'), ('10KR', '14K红'), ('SILV', '纯银'), ('S925', 'S925'), ('GONB', '铜镀金'), ('ALLO', '合金'), ('', 'N/A')], default='', max_length=4)),
            ],
            options={
                'verbose_name': '配件',
                'verbose_name_plural': '配件',
            },
            bases=('jewelry.merchandise',),
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('merchandise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jewelry.merchandise')),
                ('belongs_to_accessory', models.ForeignKey(blank=True, help_text='如果是配石', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gem', to='jewelry.accessory', verbose_name='所属空托或配件')),
            ],
            bases=('jewelry.merchandise',),
        ),
        migrations.CreateModel(
            name='Jewel',
            fields=[
                ('merchandise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jewelry.merchandise')),
                ('jewel_type', models.CharField(choices=[('', 'N/A'), ('R', '戒指'), ('项链', (('P', '项坠'), ('N', '珠链'))), ('耳饰', (('D', '耳钉'), ('G', '耳钩'), ('X', '耳线'), ('J', '耳夹'))), ('W', '手链'), ('B', '胸针'), ('H', '头饰')], default='', max_length=5)),
                ('style', models.CharField(blank=True, default='', help_text='工艺或风格系列，例如花丝、满天星', max_length=100, verbose_name='风格')),
            ],
            options={
                'verbose_name': '成品',
                'verbose_name_plural': '成品',
            },
            bases=('jewelry.merchandise',),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='付款时间')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jewelry.depot')),
                ('merchandise', models.ManyToManyField(to='jewelry.Merchandise')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jewelry.depot')),
            ],
            options={
                'verbose_name': '调货单',
                'verbose_name_plural': '调货单',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(default='', max_length=5, verbose_name='颁发机构')),
                ('code', models.CharField(default='', max_length=50, verbose_name='证书编号')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='jewelry.merchandise', verbose_name='证书')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
            },
        ),
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('gem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jewelry.gem')),
                ('color', models.CharField(choices=[('', 'N/A'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], default='', max_length=1)),
                ('clarity', models.CharField(choices=[('', 'N/A'), ('FL', 'FL'), ('IF', 'IF'), ('VVS1', 'VVS1'), ('VVS2', 'VVS2'), ('VS1', 'VS1'), ('VS2', 'VS2'), ('SI1', 'SI1'), ('SI2', 'SI2')], default='', max_length=4)),
                ('cut', models.CharField(choices=[('', 'N/A'), ('EX', 'EX'), ('VG', 'VG'), ('G', 'G')], default='', max_length=2)),
            ],
            options={
                'verbose_name': '钻石',
                'verbose_name_plural': '钻石',
            },
            bases=('jewelry.gem',),
        ),
        migrations.CreateModel(
            name='Pearl',
            fields=[
                ('gem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jewelry.gem')),
                ('pearl_type', models.CharField(choices=[('', 'N/A'), ('海水珍珠', (('AWHT', '南洋白珍珠'), ('SSGD', '南洋金珍珠'), ('TBLK', '大溪地黑珍珠'), ('AKOY', 'AKOYA'), ('MABE', '马贝珠'), ('KESH', 'KESHI'), ('CONC', '海螺珠'))), ('淡水珍珠', (('FRWT', '淡水珍珠'), ('BARQ', '巴洛克珍珠'), ('EDSN', '爱迪生珍珠')))], default='', max_length=4)),
                ('min_size', models.FloatField()),
                ('max_size', models.FloatField()),
                ('body_color', models.CharField(max_length=10, verbose_name='体色')),
                ('overtone', models.CharField(max_length=10, verbose_name='伴色')),
                ('iridescence', models.CharField(choices=[('', 'N/A'), ('A', '强'), ('B', '明显'), ('C', '一般')], default='', max_length=1, verbose_name='晕彩')),
                ('luster', models.CharField(choices=[('', 'N/A'), ('A', '极强'), ('B', '强'), ('C', '中'), ('D', '弱')], max_length=1)),
                ('surface', models.CharField(choices=[('', 'N/A'), ('A', '无瑕'), ('B', '微瑕'), ('C', '小瑕'), ('D', '瑕疵'), ('E', '重瑕')], max_length=1)),
                ('nacre', models.CharField(choices=[('', 'N/A'), ('A', '特厚'), ('B', '厚'), ('C', '中'), ('D', '薄'), ('E', '极薄')], max_length=1)),
            ],
            bases=('jewelry.gem',),
        ),
        migrations.AddField(
            model_name='gem',
            name='belongs_to_jewel',
            field=models.ForeignKey(blank=True, help_text='如果是主石', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gem', to='jewelry.jewel', verbose_name='所属成品'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='belongs_to_jewel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory', to='jewelry.jewel', verbose_name='所属成品'),
        ),
    ]
