# Generated by Django 4.0 on 2021-12-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='sku_by_supplier',
            field=models.CharField(blank=True, max_length=20, verbose_name='供应商条码'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='manufacture',
            field=models.CharField(blank=True, max_length=10, verbose_name='产地'),
        ),
    ]
