# Generated by Django 4.0 on 2021-12-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_merchandise_sku_by_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pearl',
            options={'verbose_name': '珍珠', 'verbose_name_plural': '珍珠'},
        ),
        migrations.AlterField(
            model_name='diamond',
            name='clarity',
            field=models.CharField(choices=[('', 'N/A'), ('FL', 'FL'), ('IF', 'IF'), ('VVS1', 'VVS1'), ('VVS2', 'VVS2'), ('VS1', 'VS1'), ('VS2', 'VS2'), ('SI1', 'SI1'), ('SI2', 'SI2')], default='', max_length=4, verbose_name='净度'),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='color',
            field=models.CharField(choices=[('', 'N/A'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], default='', max_length=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='cut',
            field=models.CharField(choices=[('', 'N/A'), ('EX', 'EX'), ('VG', 'VG'), ('G', 'G')], default='', max_length=2, verbose_name='切工'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instock', to='jewelry.depot', verbose_name='场所'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='sku_by_supplier',
            field=models.CharField(blank=True, max_length=20, verbose_name='厂家款号'),
        ),
        migrations.AlterField(
            model_name='pearl',
            name='luster',
            field=models.CharField(choices=[('', 'N/A'), ('A', '极强'), ('B', '强'), ('C', '中'), ('D', '弱')], max_length=1, verbose_name='光泽'),
        ),
        migrations.AlterField(
            model_name='pearl',
            name='nacre',
            field=models.CharField(choices=[('', 'N/A'), ('A', '特厚'), ('B', '厚'), ('C', '中'), ('D', '薄'), ('E', '极薄')], max_length=1, verbose_name='珠层'),
        ),
        migrations.AlterField(
            model_name='pearl',
            name='surface',
            field=models.CharField(choices=[('', 'N/A'), ('A', '无瑕'), ('B', '微瑕'), ('C', '小瑕'), ('D', '瑕疵'), ('E', '重瑕')], max_length=1, verbose_name='表皮'),
        ),
    ]
